name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shared:
    uses: pantos-io/ci-workflows/.github/workflows/python-ci.yml@v1

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - uses: pantos-io/ci-workflows/.github/actions/install-poetry@v1

        - name: Check poetry version
          run: |
            poetry --version
            ls
            make build
            ls dist